### ISSUE TITLE
Font icons are wrong

### ISSUE THREAD

**Issue by jsphkhan** [webcomponents/webcomponents-icons#2]
Font icon for Custom elements and HTML Imports are mismatched. Kindly check the attached image.
<img width="1114" alt="screen shot 2015-07-07 at 2 24 43 pm" src="https://cloud.githubusercontent.com/assets/1991609/8542549/22e45dd6-24b4-11e5-91a1-64af005c29c5.png">

**Comment by zenorocha** [comment]
Thanks for reporting @jsphkhan!
